### ISSUE TITLE
Does dagger-proguard-helper work with gradle ?

### ISSUE THREAD

**Issue by frank-fan** [idamobile/dagger-proguard-helper#1]
Hello, I try to use dagger-proguard-helper with gradle to generate proguard-keepnames.cfg, but I can't find any *.cfg generated in my project. Some help?

**Comment by frank-fan** [comment]
I download the sources of dagger-proguard-helper, and find out that dagger-proguard-helper donot work with AndroidAnnotation. Some @Module class of dagger with AndroidAnnotation generation class will cause error.
Some help?

**Comment by Jogan** [comment]
Same here wondering if this would work with gradle

**Comment by shaubert** [comment]
Hi guys. Yeap, it works for me.

```
dependencies {
    ...
    provided 'com.github.idamobile:dagger-proguard-helper-processor:1.0-SNAPSHOT'
    compile 'com.squareup.dagger:dagger:1.2.2'
    provided 'com.squareup.dagger:dagger-compiler:1.2.2'
    ...
}

...

buildTypes {
    release {
        signingConfig signingConfigs.release
        proguardFiles = [getDefaultProguardFile('proguard-android.txt'), 'proguard.cfg', 'dagger-proguard-keepnames.cfg']
        minifyEnabled true
    }
    ...
}
```

**Comment by csabatini** [comment]
Not working for me,  gradle fails to resolve. Not showing up in maven central

https://search.maven.org/#search%7Cga%7C1%7Ccom.github.idamobile

**Comment by zhanzf** [comment]
It works for me as below. 
Try to add the url.

```
repositories {
    maven {
        url "https://github.com/shaubert/maven-repo/raw/master/snapshots/"
    }
}

dependencies {
    provided 'com.github.idamobile:dagger-proguard-helper-processor:1.0.1-SNAPSHOT'
    compile 'com.squareup.dagger:dagger:1.2.2'
    provided 'com.squareup.dagger:dagger-compiler:1.2.2'
}
```

**Comment by whiteLT** [comment]
Try this:
`maven { url 'https://twittersdk.artifactoryonline.com/twittersdk/public/' }`

`kapt 'com.github.idamobile:dagger-proguard-helper-processor:1.0-SNAPSHOT'`

`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', '../dagger-proguard-keepnames.cfg'`
